---

- name: "Provision {{ cloud_provider_name }} {{ cloud_resource_type }} resources."
  local_action: "{{ item.value.module }}"
  args: "{{ item.value.options }}"
  with_dict: "{{ cloud_resources_to_provision[cloud_provider_name][cloud_resource_type] }}"
  loop_control:
    label: "{{ item.key }}"
  register: cloud_resource_provision_result

# @TODO: Update cloud_facts with changes

