---

- name: "Set human names for {{ cloud_provider_name }} {{ cloud_fact_type }} by {{ cloud_fact_key_arg }} tag."
  set_fact:
    cloud_facts: "{{ cloud_facts | default({}) | combine( { cloud_provider_name: { cloud_fact_type: { item.tags[cloud_fact_key_arg]: item } } }, recursive=True ) }}"
  with_items: "{{ cloud_lookup_facts }}"
  loop_control:
    label: "{{ item.tags[cloud_fact_key_arg] }}"

